export default {
    GET_STATIC_INDEX: 'GET_STATIC_INDEX',
    GET_DOCTOR_LIST: 'GET_DOCTOR_LIST',
    GET_RECORDER_LIST: 'GET_RECORDER_LIST',
    GET_EMPTY_MEDICAL_RECORD: 'GET_EMPTY_MEDICAL_RECORD',
    GET_MEDICAL_RECORD_LIST: 'GET_MEDICAL_RECORD_LIST',
    CHANGE_CURRENT_MEDICAL_RECORD_ID: 'CHANGE_CURRENT_MEDICAL_RECORD_ID',
}
